Add RTR to CAN header
Auterion/NuttX pull request #1
Opened 2020-05-11 09:54 UTC by cmic0

This PR adds RTR to can header.

2020-05-11 10:00 UTC, cmic0 commented
@bkueng / @davids5 can you provide feedback on this?

As I am fairly new in introducing this kind of changes, i have a couple of questions:
- would this change be OK to be upstreamed?
- Should this RTR include be enabled/disabled by setting a flag?

2020-05-11 16:06 UTC, davids5 requested changes
@cmic0 - see inline

2020-05-11 16:06 UTC, davids5 commented on arch/arm/src/stm32f7/hardware/stm32_can.h
> +#define CAN_TIR_RTR_SHIFT         (1)
The pattern is a shift and a mask for multi bit fields. 
CAN_TIR_RTR is fine as in

2020-05-11 16:06 UTC, davids5 commented on arch/arm/src/stm32f7/stm32_can.c
> +  regval |= (uint32_t)msg->cm_hdr.ch_rtr << CAN_TIR_RTR_SHIFT;
This should be 
 regval &= ~(CAN_TIR_STID_MASK | CAN_TIR_RTR);
 regval |= ( ( (uint32_t) msg->cm_hdr.ch_id << CAN_TIR_STID_SHIFT) & CAN_TIR_STID_MASK );
 'regval |= (msg->cm_hdr.ch_rtr ? CAN_TIR_RTR : 0)'

2020-05-11 16:09 UTC, davids5 commented on arch/arm/src/stm32f7/stm32_can.c
> +  regval |= (uint32_t)msg->cm_hdr.ch_rtr << CAN_TIR_RTR_SHIFT;
@cmic0 - to upstream it may need a CONFIG_CAN_USE_RTR and the and #ifdef around the code. OR an IOCTL to turn it on and off dynamically.

2020-05-12 08:04 UTC, cmic0 commented on arch/arm/src/stm32f7/stm32_can.c
> +  regval |= (uint32_t)msg->cm_hdr.ch_rtr << CAN_TIR_RTR_SHIFT;
Something i am not fully clear:
Why do we need to clear the fields if they were already cleared a couple of lines above?
https://github.com/Auterion/NuttX/blob/8f9433e5a5be919f4e75fe4382077dc3951e9442/arch/arm/src/stm32f7/stm32_can.c#L1272-L1273

2020-05-12 10:23 UTC, davids5 commented on arch/arm/src/stm32f7/stm32_can.c
> +  regval |= (uint32_t)msg->cm_hdr.ch_rtr << CAN_TIR_RTR_SHIFT;
My Bad! I did not unfold it enough to see it it cleared one line 1272. 
The code needs to be cleaned up.

2020-05-12 17:11 UTC, cmic0 commented
@davids5 with the help of @bkueng i was able to put in place the CONFIG_CAN_USE_RTR. 

How does the implementation look now?

2020-05-12 17:29 UTC, davids5 approved these changes
LGTM

2020-05-12 17:43 UTC, merged